#!/usr/bin/env python
import os
import sys

env = SConscript("godot-cpp/SConstruct")

# For reference:
# - CCFLAGS are compilation flags shared between C and C++
# - CFLAGS are for C-specific compilation flags
# - CXXFLAGS are for C++-specific compilation flags
# - CPPFLAGS are for pre-processor flags
# - CPPDEFINES are for pre-processor defines
# - LINKFLAGS are for linking flags

# EOS SDK configuration
eos_sdk = "eos_sdk"
env.Append(CPPPATH=["src/", eos_sdk + "/Include"])

if env["platform"] == "windows":
    env.Append(LIBPATH=[eos_sdk + "/Lib"])
    env.Append(LIBS=["EOSSDK-Win64-Shipping"])
elif env["platform"] == "linux":
    env.Append(LIBPATH=[eos_sdk + "/Bin"])
    env.Append(LIBS=["EOSSDK-Linux-Shipping"])

sources = Glob("src/*.cpp")

if env["platform"] == "macos":
    library = env.SharedLibrary(
        "demo/bin/libgodotepic.{}.{}.framework/libgodotepic.{}.{}".format(
            env["platform"], env["target"], env["platform"], env["target"]
        ),
        source=sources,
    )
elif env["platform"] == "ios":
    if env["ios_simulator"]:
        library = env.StaticLibrary(
            "demo/bin/libgodotepic.{}.{}.simulator.a".format(env["platform"], env["target"]),
            source=sources,
        )
    else:
        library = env.StaticLibrary(
            "demo/bin/libgodotepic.{}.{}.a".format(env["platform"], env["target"]),
            source=sources,
        )
else:
    library = env.SharedLibrary(
        "demo/bin/libgodotepic{}{}".format(env["suffix"], env["SHLIBSUFFIX"]),
        source=sources,
    )

Default(library)
