name: Build and Release GDExtension

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build-linux-x86_64:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Cache godot-cpp build
        uses: actions/cache@v4
        with:
          path: godot_eos_extension/godot-cpp/bin
          key: ${{ runner.os }}-godotcpp-${{ hashFiles('godot_eos_extension/godot-cpp/src/**', 'godot_eos_extension/godot-cpp/SConstruct', 'godot_eos_extension/godot-cpp/Makefile') }}
          restore-keys: |
            ${{ runner.os }}-godotcpp-
      - name: Download EOS SDK
        run: |
          set -euo pipefail
          curl -L -o eos_sdk.zip "${{ secrets.EOS_SDK_URL }}"
          rm -rf eos_sdk eos_sdk_tmp
          unzip -q eos_sdk.zip -d eos_sdk_tmp
          SDK_DIR=$(find eos_sdk_tmp -mindepth 1 -maxdepth 2 -type d -name SDK -print -quit)
          if [ -z "$SDK_DIR" ]; then
            echo "Failed to locate SDK directory inside EOS archive" >&2
            exit 1
          fi
          mv "$SDK_DIR" eos_sdk
          rm -rf eos_sdk_tmp eos_sdk.zip
      - name: Install SCons
        run: sudo apt-get install -y scons
      - name: Build Linux x86_64 Debug
        working-directory: godot_eos_extension
        run: scons platform=linux arch=x86_64 target=template_debug EOS_SDK_PATH=../eos_sdk
      - name: Build Linux x86_64 Release
        working-directory: godot_eos_extension
        run: scons platform=linux arch=x86_64 target=template_release EOS_SDK_PATH=../eos_sdk
      - name: Upload Linux x86_64 Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: godoteos-linux-x86_64
          path: godot_eos_extension/demo/bin/**

  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Cache godot-cpp build
        uses: actions/cache@v4
        with:
          path: godot_eos_extension/godot-cpp/bin
          key: ${{ runner.os }}-godotcpp-${{ hashFiles('godot_eos_extension/godot-cpp/src/**', 'godot_eos_extension/godot-cpp/SConstruct', 'godot_eos_extension/godot-cpp/Makefile') }}
          restore-keys: |
            ${{ runner.os }}-godotcpp-
      - name: Install SCons
        run: brew install scons
      - name: Download EOS SDK
        run: |
          set -euo pipefail
          curl -L -o eos_sdk.zip "${{ secrets.EOS_SDK_URL }}"
          rm -rf eos_sdk eos_sdk_tmp
          unzip -q eos_sdk.zip -d eos_sdk_tmp
          SDK_DIR=$(find eos_sdk_tmp -mindepth 1 -maxdepth 2 -type d -name SDK -print -quit)
          if [ -z "$SDK_DIR" ]; then
            echo "Failed to locate SDK directory inside EOS archive" >&2
            exit 1
          fi
          mv "$SDK_DIR" eos_sdk
          rm -rf eos_sdk_tmp eos_sdk.zip
      - name: Build Mac
        working-directory: godot_eos_extension
        run: scons platform=macos target=template_release EOS_SDK_PATH=../eos_sdk
      - name: Upload Mac Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: godoteos-macos
          path: godot_eos_extension/demo/bin/**

  build-windows-x86_64:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Cache godot-cpp build
        uses: actions/cache@v4
        with:
          path: godot_eos_extension/godot-cpp/bin
          key: ${{ runner.os }}-godotcpp-${{ hashFiles('godot_eos_extension/godot-cpp/src/**', 'godot_eos_extension/godot-cpp/SConstruct', 'godot_eos_extension/godot-cpp/Makefile') }}
          restore-keys: |
            ${{ runner.os }}-godotcpp-
      - name: Install SCons
        run: pip install scons
      - name: Download EOS SDK
        shell: pwsh
        run: |
          $ErrorActionPreference = 'Stop'
          $archive = 'eos_sdk.zip'
          Invoke-WebRequest -Uri '${{ secrets.EOS_SDK_URL }}' -OutFile $archive
          if (Test-Path 'eos_sdk_tmp') { Remove-Item 'eos_sdk_tmp' -Recurse -Force }
          Expand-Archive -Path $archive -DestinationPath 'eos_sdk_tmp' -Force
          $sdkDir = Get-ChildItem -Path 'eos_sdk_tmp' -Recurse -Directory -Filter 'SDK' | Select-Object -First 1
          if (-not $sdkDir) {
            throw 'Failed to locate SDK directory inside EOS archive.'
          }
          if (Test-Path 'eos_sdk') { Remove-Item 'eos_sdk' -Recurse -Force }
          Move-Item -Path $sdkDir.FullName -Destination 'eos_sdk'
          Remove-Item 'eos_sdk_tmp', $archive -Recurse -Force
      - name: Build Windows x86_64
        shell: pwsh
        working-directory: godot_eos_extension
        run: scons platform=windows arch=x86_64 target=template_release EOS_SDK_PATH=../eos_sdk
      - name: Upload Windows Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: godoteos-windows-x86_64
          path: godot_eos_extension/demo/bin/**

  release:
    needs:
      - build-linux-x86_64
      - build-macos
      - build-windows-x86_64
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Linux artifacts
        uses: actions/download-artifact@v4
        continue-on-error: true
        with:
          name: godoteos-linux-x86_64
          path: artifacts/linux/x86_64

      - name: Download Mac artifacts
        uses: actions/download-artifact@v4
        continue-on-error: true
        with:
          name: godoteos-macos
          path: artifacts/macos

      - name: Download Windows artifacts
        uses: actions/download-artifact@v4
        continue-on-error: true
        with:
          name: godoteos-windows-x86_64
          path: artifacts/windows/x86_64

      - name: Create bin directories in addons
        run: |
          mkdir -p addons/godoteos/bin/linux
          mkdir -p addons/godoteos/bin/macos
          mkdir -p addons/godoteos/bin/windows

      - name: Copy downloaded build artifacts into addons
        run: |
          set -e
          if [ -d artifacts/linux/x86_64 ]; then
            cp -a artifacts/linux/x86_64/. addons/godoteos/bin/linux/ || true
          fi
          if [ -d artifacts/macos ]; then
            cp -a artifacts/macos/. addons/godoteos/bin/macos/ || true
          fi
          if [ -d artifacts/windows/x86_64 ]; then
            cp -a artifacts/windows/x86_64/. addons/godoteos/bin/windows/ || true
          fi

      - name: Show contents of addons/bin for debug
        run: |
          echo "Listing addons/godoteos/bin"
          ls -R addons/godoteos/bin || true

      - name: Zip entire addons folder with tag name
        shell: bash
        run: zip -r "GodotEOS_${{ github.ref_name }}.zip" addons

      - name: Create Release with named zip
        uses: softprops/action-gh-release@v2
        with:
          files: GodotEOS_${{ github.ref_name }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
